### ISSUE TITLE
run= runs 2x the same thing somehow

### ISSUE THREAD

**Issue by lostallmymoney** [RaulPPelaez/Naga_KeypadMapper#53]
I'm able to fix it for my usages but it's an additional patch on my things for almost nothing lol. Naga service isn't running 2x so that can't be the problem. Maybe it's because my mouse shows 4 times in xinput ?? pls help. 
![screenshot from 2018-04-03 11-03-26](https://user-images.githubusercontent.com/6634309/38257735-ccdd5b0a-372e-11e8-9372-81fc7bd9ecb8.png)

**Comment by RaulPPelaez** [comment]
Ups I think I know what is happening, let me check...
No clue about the mouse showing 4 times though...

**Comment by RaulPPelaez** [comment]
Yep, I introduced a bug in the previous commit that caused most actions to be performed when the key was pressed and released.
It should be fixed now. Please let me know otherwise.
Sorry!

**Comment by RaulPPelaez** [comment]
Well you can put the run action twice! (remember you can have macros). Or just make "run" run the script twice with something like:
9-run=cat myScript.bash myScript.bash | bash
Keep in mind that I am just making this up, I do not know if this will actually work!

**Comment by dannyss6** [comment]
Yeah you can run the action twice but what is interesting is having the possibility to run it once when you release the button with the time interval that you want. Also I'm not sure you fixed the bug i still have it on my side :/

**Comment by dannyss6** [comment]
I might make my own fork also if you don't mind

**Comment by dannyss6** [comment]
Also I'm not sure but I think adding spaces in the run='' doesn't work and they end up deleted so I need to points it towards a .desktop that points to my .sh

**Comment by RaulPPelaez** [comment]
Well shit... It should definetly not run the "run" command on release, I do not know what is happening then... I do not have a naga mouse right now so I am testing with a keyboard, but the testing code is a little brittle so maybe I messed up somewhere.
Maybe this is related with your mouse showing up 4 times instead of 2? I'm clueless about that. It is curious the amount of different behaviors and things people get, so many details!

You are right about the press/release thing, had not thought about it that way... I can see that being useful, I'll keep it in mind.

Yes please do your fork that is what it is about. But if you find something interesting let me know!

About the spaces, have you put the command between quotes? I remember running scripts with "bash script.bash" without issues.

**Comment by dannyss6** [comment]
I fixed the space problem. You removed all the ' ' in the line even after =. I changed that.
Also I added run2 (press/release) and run3 (without setsid because i'm trying to fix an issue where running a script with notify-send doesn't send the notifications ( i think it has to do with the users )). Here's the file if you want to copy/paste just the fix : 
[naga.zip](https://github.com/RaulPPelaez/Naga_KeypadMapper/files/1874558/naga.zip)

**Comment by RaulPPelaez** [comment]
Yes you are right! Thank you!
Could you make a pull request? If you dont feel like it I'll just manually add the changes.

**Comment by lostallmymoney** [comment]
I changed many things but here's the patch 
`string line, line1, token1;
    int pos;
    while (getline(in, line)) {

      pos = line.find('=');
      line1 = line.substr(0, pos); //line1 = numbers and stull

      line.erase(0, pos+1); //line = command
      line1.erase(std::remove(line1.begin(), line1.end(), ' '), line1.end()); //Erase spaces

      if (line1[0] == '#') //Ignore comments
      continue;

      //Search option and argument
      pos = line1.find("-");
      token1 = line1.substr(0, pos);
      line1 = line1.substr(pos + 1);

      //Encode and store mapping
      pos = stoi(token1) - 1;`

**Comment by RaulPPelaez** [comment]
Ok thanks, I included it in the source, I put a comment with your name so you get credited somehow at least!
I borrowed a naga so I could test better. I fixed some issues with the toggle command as well and added your run2 command.
It should be all working correctly now. Let me know otherwise.
 
Thanks for your help!

**Comment by swapsCAPS** [comment]
w00t! Also fixed for me : )
```
Ubuntu Gnome 16.04
Naga Epic Chroma
```
Thanks!

**Comment by RaulPPelaez** [comment]
I considered this fixed in 4204a482f338dcfd4f6a1d4e4bccae7a20821d90
